import { StyleSheet } from "react-native";

export const scheduleStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#161622",
    padding: 16,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 20,
  },
  taskContainer: {
    flexDirection: "row",
    justifyContent: "space-around",
    marginBottom: 20,
  },
  taskButton: {
    alignItems: "center",
    backgroundColor: "#065F46",
    padding: 16,
    borderRadius: 12,
    width: "30%",
  },
  taskIcon: {
    fontSize: 24,
    marginBottom: 8,
  },
  taskText: {
    color: "#FFFFFF",
    fontSize: 14,
  },
  modalContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    padding: 16,
  },
  modalContent: {
    backgroundColor: "#1F2937",
    borderRadius: 16,
    width: "100%",
    maxHeight: "80%",
    padding: 20,
  },
  modalHeader: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: "#374151",
  },
  modalHeaderTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 16,
    textAlign: "center",
  },
  modalHeaderSubtitle: {
    color: "#A7AFB5",
    fontSize: 12,
    marginTop: 4,
    textAlign: "center",
  },
  plantTypeScrollView: {
    flex: 1,
    width: "100%",
  },
  plantTypeScrollContent: {
    padding: 16,
  },
  plantTypeGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
    alignItems: "flex-start",
    width: "100%",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 16,
    padding: 16,
  },
  plantTypeCard: {
    width: "47%",
    aspectRatio: 1.2,
    borderRadius: 16,
    padding: 16,
    marginBottom: 0,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
    borderWidth: 2,
    borderColor: "rgba(255, 255, 255, 0.15)",
    backgroundColor: "rgba(0, 0, 0, 0.2)",
  },
  plantTypeHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 12,
  },
  plantTypeIconContainer: {
    padding: 12,
    borderRadius: 12,
  },
  plantTypeIcon: {
    fontSize: 28,
  },
  plantTypeTag: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
  },
  plantTypeTagText: {
    fontSize: 12,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  plantTypeInfo: {
    flex: 1,
    justifyContent: "space-between",
  },
  plantTypeName: {
    color: "#FFFFFF",
    fontSize: 20,
    fontWeight: "bold",
    marginBottom: 6,
  },
  plantTypeDescription: {
    color: "rgba(255, 255, 255, 0.8)",
    fontSize: 13,
    lineHeight: 18,
    marginBottom: 12,
  },
  plantTypeStats: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 16,
  },
  statIconContainer: {
    backgroundColor: "rgba(6, 95, 70, 0.2)",
    padding: 8,
    borderRadius: 8,
    marginRight: 12,
  },
  statInfo: {
    flex: 1,
  },
  statValue: {
    color: "#FFFFFF",
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 2,
  },
  statLabel: {
    color: "#9CA3AF",
    fontSize: 12,
    textTransform: "uppercase",
  },
  enhancedStatCard: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#374151",
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  statIconContainer: {
    backgroundColor: "rgba(6, 95, 70, 0.2)",
    padding: 8,
    borderRadius: 8,
    marginRight: 12,
  },
  plantTypeStatLast: {
    borderRightWidth: 0,
  },
  plantTypeStatIcon: {
    fontSize: 16,
    marginBottom: 4,
  },
  plantTypeStatValue: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 2,
  },
  plantTypeStatLabel: {
    color: "#9CA3AF",
    fontSize: 11,
    textTransform: "uppercase",
    textAlign: "center",
  },
  divider: {
    width: 1,
    height: 24,
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    marginHorizontal: 8,
  },
  closeButton: {
    backgroundColor: "#374151",
    padding: 16,
    alignItems: "center",
    borderTopWidth: 1,
    borderTopColor: "#374151",
  },
  closeButtonText: {
    color: "#FFFFFF",
    textAlign: "center",
    fontWeight: "bold",
  },
  plantTypeButton: {
    backgroundColor: "#065F46",
    padding: 16,
    borderRadius: 8,
    marginBottom: 8,
  },
  plantTypeExamples: {
    color: "#A7AFB5",
    fontSize: 12,
    marginTop: 4,
  },
  scheduleItem: {
    backgroundColor: "#1F2937",
    borderRadius: 8,
    marginBottom: 8,
  },
  scheduleContent: {
    padding: 30,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  scheduleText: {
    color: "#FFFFFF",
    fontSize: 16,
    marginBottom: 4,
  },
  plantTypeText: {
    color: "#A7AFB5",
    fontSize: 14,
    marginBottom: 4,
  },
  scheduleDate: {
    color: "#9CA3AF",
    fontSize: 14,
    fontWeight: "500",
    marginTop: 4,
    marginBottom: 4,
  },
  deleteButton: {
    padding: 8,
  },
  deleteButtonText: {
    fontSize: 20,
  },
  cancelButton: {
    backgroundColor: "#DC2626",
    padding: 12,
    borderRadius: 8,
    marginTop: 8,
  },
  cancelButtonText: {
    color: "#FFFFFF",
    textAlign: "center",
    fontWeight: "bold",
  },
  addButton: {
    backgroundColor: "#065F46",
    padding: 16,
    borderRadius: 12,
    marginBottom: 20,
  },
  addButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
    textAlign: "center",
  },
  careInstructions: {
    color: "#A7AFB5",
    fontSize: 12,
    marginTop: 4,
    fontStyle: "italic",
  },
  activePlantsSection: {
    backgroundColor: "#1F2937",
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  activePlantsHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 20,
  },
  activePlantsTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#FFFFFF",
  },
  activePlantsCount: {
    backgroundColor: "#065F46",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 20,
  },
  activePlantsCountText: {
    color: "#FFFFFF",
    fontWeight: "600",
    fontSize: 14,
  },
  plantsGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 16,
  },
  plantCard: {
    width: "48%",
    backgroundColor: "#2D3748",
    borderRadius: 12,
    padding: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  plantIcon: {
    fontSize: 32,
    marginBottom: 12,
  },
  plantName: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 4,
  },
  plantStage: {
    color: "#9CA3AF",
    fontSize: 14,
    marginBottom: 12,
  },
  plantProgress: {
    height: 4,
    backgroundColor: "#374151",
    borderRadius: 2,
    marginBottom: 12,
    overflow: "hidden",
  },
  plantProgressFill: {
    height: "100%",
    backgroundColor: "#065F46",
    borderRadius: 2,
  },
  plantStats: {
    flexDirection: "row",
    justifyContent: "space-between",
    gap: 12,
    marginTop: 16,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 12,
  },
  plantChip: {
    backgroundColor: "#065F46",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    marginRight: 8,
  },
  plantChipText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "500",
  },
  careDetailsContainer: {
    flex: 1,
  },
  careDetailsCard: {
    backgroundColor: "#1F2937",
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  cardHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  cardTitle: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 16,
    textAlign: "center",
  },
  careSection: {
    marginBottom: 24,
  },
  careSectionHeader: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 12,
  },
  careSectionIcon: {
    fontSize: 24,
    marginRight: 8,
  },
  careSectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#FFFFFF",
  },
  careDetailBox: {
    backgroundColor: "#2D3748",
    borderRadius: 12,
    padding: 16,
  },
  careDetailItem: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#4B5563",
  },
  careDetailLabel: {
    color: "#9CA3AF",
    fontSize: 14,
  },
  careDetailValue: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "500",
  },
  timelineContainer: {
    backgroundColor: "#2D3748",
    borderRadius: 12,
    padding: 16,
  },
  timelineItem: {
    marginBottom: 16,
  },
  timelinePhase: {
    color: "#9CA3AF",
    fontSize: 14,
    marginBottom: 4,
  },
  timelineDays: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "500",
    marginBottom: 4,
  },
  timelineBar: {
    height: 4,
    backgroundColor: "#065F46",
    borderRadius: 2,
  },
  totalTimeContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 16,
    paddingTop: 12,
    borderTopWidth: 1,
    borderTopColor: "#4B5563",
  },
  totalTimeLabel: {
    color: "#9CA3AF",
    fontSize: 14,
  },
  totalTimeValue: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  varietiesContainer: {
    flex: 1,
    width: "100%",
  },
  varietiesScrollView: {
    flex: 1,
    width: "100%",
    maxHeight: "80%",
  },
  varietiesGrid: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 12,
    padding: 16,
    justifyContent: "flex-start",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    borderRadius: 16,
  },
  varietyChip: {
    backgroundColor: "#065F46",
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
  },
  varietyText: {
    color: "#FFFFFF",
    fontSize: 14,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
    backgroundColor: "#1F2937",
    borderRadius: 16,
    marginBottom: 24,
  },
  loadingText: {
    color: "#FFFFFF",
    marginTop: 12,
    fontSize: 16,
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
  },
  errorText: {
    color: "#DC2626",
    fontSize: 16,
    marginBottom: 16,
  },
  retryButton: {
    backgroundColor: "#065F46",
    padding: 12,
    borderRadius: 8,
  },
  retryButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "bold",
  },
  plantTypeDisabled: {
    opacity: 0.5,
  },
  activePlantStatus: {
    backgroundColor: "#1F2937",
    borderRadius: 16,
    padding: 20,
    marginBottom: 24,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  plantHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  plantInfo: {
    flex: 1,
  },
  plantedDate: {
    color: "#9CA3AF",
    fontSize: 14,
  },
  harvestButton: {
    backgroundColor: "#065F46",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
    flexDirection: "row",
    alignItems: "center",
  },
  harvestButtonText: {
    color: "#FFFFFF",
    fontWeight: "600",
    marginLeft: 4,
  },
  plantActions: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
    gap: 12,
  },
  actionButton: {
    flex: 1,
    backgroundColor: "#374151",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    marginHorizontal: 6,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  actionButtonIcon: {
    fontSize: 24,
    marginBottom: 8,
  },
  actionButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "500",
  },
  dangerButton: {
    backgroundColor: "#991B1B",
  },
  careDetailsSection: {
    marginTop: 20,
  },
  scheduleSection: {
    marginTop: 20,
  },
  scheduleList: {
    marginTop: 20,
  },
  varietyCard: {
    backgroundColor: "#2D3748",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    width: "48%",
    marginBottom: 12,
  },
  varietyIcon: {
    fontSize: 32,
    marginBottom: 8,
  },
  varietyName: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 8,
    textAlign: "center",
  },
  varietyBadge: {
    backgroundColor: "#065F46",
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 4,
  },
  varietyBadgeText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "600",
  },
  varietyIconContainer: {
    backgroundColor: "#065F46",
    padding: 8,
    borderRadius: 8,
    marginBottom: 8,
  },
  varietyIcon: {
    fontSize: 32,
  },
  enhancedModalContent: {
    backgroundColor: "#1F2937",
    borderRadius: 20,
    width: "95%",
    maxWidth: 600,
    maxHeight: "90%",
    padding: 16,
  },
  enhancedModalHeader: {
    marginBottom: 24,
  },
  enhancedModalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 8,
    textAlign: "center",
  },
  enhancedPlantTypeName: {
    color: "#9CA3AF",
    fontSize: 16,
    textAlign: "center",
  },
  enhancedCareTypeSelection: {
    flexDirection: "row",
    backgroundColor: "#374151",
    borderRadius: 12,
    padding: 4,
    marginBottom: 24,
  },
  enhancedCareTypeTabActive: {
    backgroundColor: "#065F46",
  },
  enhancedCareTypeTextActive: {
    color: "#FFFFFF",
  },
  enhancedCareDetailsScroll: {
    marginBottom: 24,
  },
  enhancedDefaultCareContainer: {
    backgroundColor: "#2D3748",
    borderRadius: 12,
    padding: 20,
  },
  enhancedCareSection: {
    marginBottom: 24,
  },
  enhancedCareSectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#FFFFFF",
    marginBottom: 16,
  },
  enhancedCareDetailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#4B5563",
  },
  iconContainer: {
    backgroundColor: "#374151",
    borderRadius: 8,
    padding: 8,
    marginRight: 12,
  },
  enhancedDetailIcon: {
    fontSize: 16,
  },
  enhancedDetailLabel: {
    color: "#D1D5DB",
    fontSize: 16,
  },
  valueContainer: {
    backgroundColor: "#374151",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  enhancedDetailValue: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  unitText: {
    color: "#9CA3AF",
    fontSize: 14,
  },
  enhancedRecommendedNote: {
    backgroundColor: "#374151",
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    marginTop: 16,
  },
  enhancedRecommendedText: {
    color: "#D1D5DB",
    fontSize: 14,
    flex: 1,
    marginLeft: 12,
  },
  enhancedCustomCareForm: {
    backgroundColor: "#2D3748",
    borderRadius: 12,
    padding: 20,
  },
  enhancedInputLabel: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "500",
    marginBottom: 8,
  },
  inputIcon: {
    marginRight: 8,
  },
  enhancedInput: {
    backgroundColor: "#374151",
    color: "#FFFFFF",
    padding: 12,
    borderRadius: 8,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#4B5563",
  },
  enhancedSuggestion: {
    color: "#9CA3AF",
    fontSize: 14,
    marginTop: 6,
    fontStyle: "italic",
  },
  enhancedModalFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  enhancedSecondaryButton: {
    flex: 1,
    backgroundColor: "#374151",
    padding: 16,
    borderRadius: 12,
    marginRight: 8,
  },
  enhancedPrimaryButton: {
    backgroundColor: "#065F46",
    padding: 16,
    borderRadius: 12,
    marginTop: 16,
  },
  enhancedPrimaryButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  sectionIcon: {
    marginRight: 8,
  },
  modalHeaderWithClose: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
    marginBottom: 20,
  },
  modalTitleContainer: {
    flex: 1,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 4,
  },
  modalSubtitle: {
    color: "#9CA3AF",
    fontSize: 14,
  },
  closeIconButton: {
    padding: 8,
    marginLeft: 16,
  },
  closeIcon: {
    color: "#9CA3AF",
    fontSize: 20,
    fontWeight: "500",
  },
  backIcon: {
    color: "#FFFFFF",
    fontSize: 24,
    marginRight: 16,
  },
  enhancedVarietyCard: {
    width: "31%",
    backgroundColor: "#2D3748",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  varietyMetrics: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    padding: 8,
    borderRadius: 8,
    width: "100%",
  },
  varietyMetric: {
    alignItems: "center",
    flex: 1,
  },
  metricIcon: {
    fontSize: 14,
    marginBottom: 4,
  },
  metricValue: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "600",
  },
  headerWithBack: {
    flexDirection: "row",
    alignItems: "center",
  },
  backButton: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    padding: 8,
    borderRadius: 8,
    marginRight: 12,
  },
  backButtonText: {
    fontSize: 20,
  },
  careTypeSelection: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 20,
  },
  careTypeButton: {
    flex: 1,
    padding: 12,
    borderRadius: 8,
    backgroundColor: "#2D3748",
    marginHorizontal: 4,
  },
  careTypeButtonActive: {
    backgroundColor: "#065F46",
  },
  careTypeButtonText: {
    color: "#FFFFFF",
    textAlign: "center",
    fontWeight: "600",
  },
  customCareForm: {
    maxHeight: 400,
  },
  inputGroup: {
    marginBottom: 16,
  },
  inputLabel: {
    color: "#FFFFFF",
    marginBottom: 8,
  },
  input: {
    backgroundColor: "#2D3748",
    color: "#FFFFFF",
    padding: 12,
    borderRadius: 8,
  },
  suggestion: {
    color: "#9CA3AF",
    fontSize: 12,
    marginTop: 4,
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
  },
  submitButton: {
    backgroundColor: "#065F46",
    padding: 12,
    borderRadius: 8,
    flex: 1,
    marginLeft: 8,
  },
  buttonText: {
    color: "#FFFFFF",
    textAlign: "center",
    fontWeight: "600",
  },
  growthProgressCard: {
    backgroundColor: "#1F2937",
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
  },
  growthHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 16,
  },
  growthTitleContainer: {
    flexDirection: "row",
    alignItems: "center",
  },
  growthTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginRight: 12,
  },
  stageBadge: {
    backgroundColor: "#065F46",
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 12,
  },
  stageBadgeText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "600",
    textTransform: "capitalize",
  },
  daysCount: {
    color: "#9CA3AF",
    fontSize: 16,
  },
  progressBarContainer: {
    marginBottom: 24,
  },
  progressBar: {
    height: 8,
    backgroundColor: "#374151",
    borderRadius: 4,
    marginBottom: 8,
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#065F46",
    borderRadius: 4,
  },
  progressLabels: {
    flexDirection: "row",
    justifyContent: "space-between",
  },
  progressLabel: {
    color: "#9CA3AF",
    fontSize: 12,
  },
  growthStagesContainer: {
    marginTop: 16,
  },
  growthStage: {
    marginBottom: 16,
  },
  stageIconContainer: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 8,
  },
  stageIcon: {
    fontSize: 20,
    marginRight: 8,
  },
  stageIndicator: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: "#4B5563",
  },
  activeStageIndicator: {
    backgroundColor: "#065F46",
  },
  stageName: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "500",
    marginBottom: 4,
    textTransform: "capitalize",
  },
  stageDuration: {
    color: "#9CA3AF",
    fontSize: 12,
    marginBottom: 8,
  },
  stageProgressBar: {
    height: 4,
    backgroundColor: "#374151",
    borderRadius: 2,
  },
  stageProgressFill: {
    height: "100%",
    backgroundColor: "#065F46",
    borderRadius: 2,
  },
  modalHeader: {
    borderBottomWidth: 1,
    borderBottomColor: "#374151",
    paddingBottom: 16,
    marginBottom: 20,
  },
  plantTypeName: {
    color: "#9CA3AF",
    fontSize: 14,
    marginTop: 4,
  },
  careTypeTab: {
    flex: 1,
    paddingVertical: 12,
    paddingHorizontal: 16,
    borderRadius: 8,
    backgroundColor: "#1F2937",
    marginHorizontal: 4,
  },
  careTypeTabActive: {
    backgroundColor: "#065F46",
  },
  careTypeText: {
    color: "#9CA3AF",
    textAlign: "center",
    fontWeight: "600",
  },
  careTypeTextActive: {
    color: "#FFFFFF",
  },
  careDetailsScroll: {
    maxHeight: 400,
  },
  defaultCareContainer: {
    backgroundColor: "#1F2937",
    borderRadius: 12,
    padding: 16,
  },
  careSection: {
    marginBottom: 24,
  },
  careSectionTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 12,
  },
  careDetailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#374151",
  },
  careDetailLeft: {
    flexDirection: "row",
    alignItems: "center",
  },
  careDetailIcon: {
    fontSize: 18,
    marginRight: 8,
  },
  recommendedNote: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#374151",
    padding: 12,
    borderRadius: 8,
    marginTop: 16,
  },
  recommendedIcon: {
    fontSize: 20,
    marginRight: 8,
  },
  recommendedText: {
    color: "#9CA3AF",
    fontSize: 12,
    flex: 1,
  },
  modalFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
    paddingTop: 16,
    borderTopWidth: 1,
    borderTopColor: "#374151",
  },
  primaryButton: {
    backgroundColor: "#065F46",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    flex: 1,
    marginLeft: 8,
  },
  primaryButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  secondaryButton: {
    backgroundColor: "#374151",
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    flex: 1,
    marginRight: 8,
  },
  secondaryButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  input: {
    backgroundColor: "#374151",
    color: "#FFFFFF",
    padding: 12,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#4B5563",
  },
  suggestion: {
    color: "#9CA3AF",
    fontSize: 12,
    marginTop: 4,
    fontStyle: "italic",
  },
  modalHeader: {
    borderBottomWidth: 1,
    borderBottomColor: "#374151",
    paddingBottom: 16,
    marginBottom: 20,
  },
  modalHeaderTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 16,
    textAlign: "center",
  },
  modalHeaderSubtitle: {
    color: "#9CA3AF",
    fontSize: 14,
    textAlign: "center",
  },
  plantTypeList: {
    marginBottom: 20,
  },
  plantTypeCard: {
    backgroundColor: "#1F2937",
    padding: 16,
    borderRadius: 8,
    marginBottom: 8,
  },
  plantTypeIconContainer: {
    backgroundColor: "#065F46",
    padding: 8,
    borderRadius: 8,
    marginBottom: 8,
  },
  plantTypeInfo: {
    flex: 1,
  },
  plantTypeStats: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  plantTypeStat: {
    alignItems: "center",
  },
  plantTypeStatLabel: {
    color: "#9CA3AF",
    fontSize: 12,
    marginBottom: 2,
  },
  plantTypeStatValue: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "500",
  },
  closeButton: {
    backgroundColor: "#374151",
    padding: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  closeButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  varietiesContainer: {
    marginBottom: 20,
  },
  headerWithBack: {
    flexDirection: "row",
    alignItems: "center",
  },
  backButton: {
    padding: 8,
  },
  backButtonText: {
    fontSize: 20,
  },
  varietyBadge: {
    backgroundColor: "#065F46",
    paddingHorizontal: 4,
    paddingVertical: 2,
    borderRadius: 4,
  },
  varietyBadgeText: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "600",
  },
  varietyIconContainer: {
    backgroundColor: "#065F46",
    padding: 8,
    borderRadius: 8,
    marginBottom: 8,
  },
  varietyIcon: {
    fontSize: 32,
  },
  enhancedModalContent: {
    backgroundColor: "#1F2937",
    borderRadius: 20,
    width: "95%",
    maxWidth: 600,
    maxHeight: "90%",
    padding: 16,
  },
  enhancedModalHeader: {
    marginBottom: 24,
  },
  enhancedModalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 8,
    textAlign: "center",
  },
  enhancedPlantTypeName: {
    color: "#9CA3AF",
    fontSize: 16,
    textAlign: "center",
  },
  enhancedCareTypeSelection: {
    flexDirection: "row",
    backgroundColor: "#374151",
    borderRadius: 12,
    padding: 4,
    marginBottom: 24,
  },
  enhancedCareTypeTabActive: {
    backgroundColor: "#065F46",
  },
  enhancedCareTypeTextActive: {
    color: "#FFFFFF",
  },
  enhancedCareDetailsScroll: {
    marginBottom: 24,
  },
  enhancedDefaultCareContainer: {
    backgroundColor: "#2D3748",
    borderRadius: 12,
    padding: 20,
  },
  enhancedCareSection: {
    marginBottom: 24,
  },
  enhancedCareSectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#FFFFFF",
    marginBottom: 16,
  },
  enhancedCareDetailRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#4B5563",
  },
  iconContainer: {
    backgroundColor: "#374151",
    borderRadius: 8,
    padding: 8,
    marginRight: 12,
  },
  enhancedDetailIcon: {
    fontSize: 16,
  },
  enhancedDetailLabel: {
    color: "#D1D5DB",
    fontSize: 16,
  },
  valueContainer: {
    backgroundColor: "#374151",
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 6,
  },
  enhancedDetailValue: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  unitText: {
    color: "#9CA3AF",
    fontSize: 14,
  },
  enhancedRecommendedNote: {
    backgroundColor: "#374151",
    borderRadius: 12,
    padding: 16,
    flexDirection: "row",
    alignItems: "center",
    marginTop: 16,
  },
  enhancedRecommendedText: {
    color: "#D1D5DB",
    fontSize: 14,
    flex: 1,
    marginLeft: 12,
  },
  enhancedCustomCareForm: {
    backgroundColor: "#2D3748",
    borderRadius: 12,
    padding: 20,
  },
  enhancedInputLabel: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "500",
    marginBottom: 8,
  },
  inputIcon: {
    marginRight: 8,
  },
  enhancedInput: {
    backgroundColor: "#374151",
    color: "#FFFFFF",
    padding: 12,
    borderRadius: 8,
    fontSize: 16,
    borderWidth: 1,
    borderColor: "#4B5563",
  },
  enhancedSuggestion: {
    color: "#9CA3AF",
    fontSize: 14,
    marginTop: 6,
    fontStyle: "italic",
  },
  enhancedModalFooter: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
  },
  enhancedSecondaryButton: {
    flex: 1,
    backgroundColor: "#374151",
    padding: 16,
    borderRadius: 12,
    marginRight: 8,
  },
  enhancedPrimaryButton: {
    backgroundColor: "#065F46",
    padding: 16,
    borderRadius: 12,
    marginTop: 16,
  },
  enhancedPrimaryButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    textAlign: "center",
  },
  sectionIcon: {
    marginRight: 8,
  },
  modalHeaderWithClose: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-start",
    paddingBottom: 16,
    borderBottomWidth: 1,
    borderBottomColor: "rgba(255, 255, 255, 0.1)",
    marginBottom: 20,
  },
  modalTitleContainer: {
    flex: 1,
  },
  modalTitle: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#FFFFFF",
    marginBottom: 4,
  },
  modalSubtitle: {
    color: "#9CA3AF",
    fontSize: 14,
  },
  closeIconButton: {
    padding: 8,
    marginLeft: 16,
  },
  closeIcon: {
    color: "#9CA3AF",
    fontSize: 20,
    fontWeight: "500",
  },
  backIcon: {
    color: "#FFFFFF",
    fontSize: 24,
    marginRight: 16,
  },
  enhancedVarietyCard: {
    width: "31%",
    backgroundColor: "#2D3748",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.15)",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 5,
  },
  varietyMetrics: {
    flexDirection: "row",
    justifyContent: "center",
    alignItems: "center",
    gap: 12,
    backgroundColor: "rgba(0, 0, 0, 0.2)",
    padding: 8,
    borderRadius: 8,
    width: "100%",
  },
  varietyMetric: {
    alignItems: "center",
    flex: 1,
  },
  metricIcon: {
    fontSize: 14,
    marginBottom: 4,
  },
  metricValue: {
    color: "#FFFFFF",
    fontSize: 12,
    fontWeight: "600",
  },
  varietiesScrollView: {
    flex: 1,
  },
  headerIconContainer: {
    backgroundColor: "rgba(255, 255, 255, 0.1)",
    padding: 12,
    borderRadius: 12,
    marginRight: 12,
  },
  headerIcon: {
    fontSize: 24,
  },
  growthProgressContainer: {
    backgroundColor: "#2D3748",
    borderRadius: 12,
    padding: 16,
    marginVertical: 16,
  },
  stageHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    marginBottom: 8,
  },
  currentStage: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
  progressBar: {
    height: 8,
    backgroundColor: "#374151",
    borderRadius: 4,
    overflow: "hidden",
  },
  progressFill: {
    height: "100%",
    backgroundColor: "#065F46",
    borderRadius: 4,
  },
  progressText: {
    color: "#9CA3AF",
    fontSize: 14,
  },
  plantMetrics: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 16,
    padding: 12,
    backgroundColor: "#1F2937",
    borderRadius: 12,
  },
  metricItem: {
    alignItems: "center",
    flex: 1,
  },
  metricIcon: {
    fontSize: 20,
    marginBottom: 4,
  },
  metricValue: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "bold",
    marginBottom: 2,
  },
  metricLabel: {
    color: "#9CA3AF",
    fontSize: 11,
    textTransform: "uppercase",
  },
  actionButton: {
    flex: 1,
    backgroundColor: "#374151",
    padding: 16,
    borderRadius: 12,
    alignItems: "center",
    marginHorizontal: 6,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  dangerButton: {
    backgroundColor: "#991B1B",
  },
  actionButtonIcon: {
    fontSize: 24,
    marginBottom: 8,
  },
  actionButtonText: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "500",
  },
  markAsDiedModalContent: {
    backgroundColor: "#1F2937",
    borderRadius: 16,
    width: "90%",
    padding: 20,
    maxHeight: "80%",
  },
  deathReasonContainer: {
    marginTop: 16,
    gap: 12,
  },
  deathReasonButton: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#374151",
    padding: 16,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
  },
  deathReasonIcon: {
    fontSize: 24,
    marginRight: 16,
  },
  deathReasonTextContainer: {
    flex: 1,
  },
  deathReasonTitle: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 4,
  },
  deathReasonDescription: {
    color: "#9CA3AF",
    fontSize: 14,
  },
  inputDisabled: {
    opacity: 0.5,
    backgroundColor: "#374151",
  },
  enhancedInput: {
    backgroundColor: "#1F2937",
    borderRadius: 8,
    padding: 12,
    color: "#FFFFFF",
    fontSize: 16,
    borderWidth: 1,
    borderColor: "rgba(255, 255, 255, 0.1)",
    marginVertical: 8,
  },
  inputGroup: {
    marginBottom: 20,
  },
  enhancedInputLabel: {
    color: "#FFFFFF",
    fontSize: 14,
    marginBottom: 4,
    fontWeight: "500",
  },
  enhancedSuggestion: {
    color: "#9CA3AF",
    fontSize: 12,
    marginTop: 4,
  },
  phRangeContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    width: "25%",
    paddingVertical: 8,
  },
  phBarContainer: {
    flex: 1,
    marginHorizontal: 12,
  },
  phBar: {
    height: 8,
    backgroundColor: "#374151",
    borderRadius: 4,
    position: "relative",
    overflow: "hidden",
  },
  phIndicator: {
    position: "absolute",
    height: "100%",
    backgroundColor: "#065F46",
    borderRadius: 4,
  },
  phScale: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 4,
  },
  phScaleLabel: {
    color: "#9CA3AF",
    fontSize: 10,
    textAlign: "center",
  },
  phValue: {
    color: "#FFFFFF",
    fontSize: 14,
    fontWeight: "600",
    backgroundColor: "#374151",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 4,
    minWidth: 40,
    textAlign: "center",
  },
  modalButtonContainer: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 20,
    paddingHorizontal: 10,
  },
  modalButton: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 8,
    marginHorizontal: 5,
    alignItems: "center",
  },
  modalCancelButton: {
    backgroundColor: "#6B7280",
  },
  modalConfirmButton: {
    backgroundColor: "#065F46",
  },
  modalButtonText: {
    color: "#FFFFFF",
    fontSize: 16,
    fontWeight: "600",
  },
});
